version: '3.7'

volumes:
  minio_data:
    name: minio_data

networks:
  minio_net:
    driver: bridge

services:

 minio-server:
  image: minio/minio
  restart: always
  volumes:
   - minio_data:/data
  networks:
    - minio_net
  ports:
    - '9000:9000'
    - '9001:9001'
  environment:
   MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
   MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
  command: server /data --console-address ":9001"

 minio-mc:
   image: minio/mc
   depends_on:
     - minio-server
   networks:
     - minio_net
   entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio minio123;
      /usr/bin/mc mb myminio/somebucketname;
      /usr/bin/mc policy set public myminio/somebucketname;
      exit 0;" 


